api_url: "https://idealab.alibaba-inc.com/api/openai/v1"
api_key: "9b3620d0054469e39746c0a39eb862f0"

model_name: "qwen3-coder-plus"
output_dir: "./outputs"
max_turns: 1000
max_retry: 100

use_skills: true
skill_path: "./skills/enhanced-ehr-sql/SKILL.md"

parquet_path: "./data/Swe-bench_Verified/test-00000-of-00001.parquet"

attack_config:
  device: "cuda"
  embedding_model_name: "dpr-ctx_encoder-single-nq-base"
  embedding_model_path: "data/model_cache/dpr-ctx_encoder-single-nq-base"
  trigger_length: 20
  trigger: "This is a special instruction!"
  lr: 5.0e-6
  num_iter: 5000
  ppl_path: "data/model_cache/gpt2"
  tool_shema_path: "data/default_tools_schema.json"
  train_path: "data/ehrsql/eicu_train.json"
  batch_size: 512
  num_cand: 50
  lam: 0.1

